name: CrashTheCastle
main: me.PureIndianSkillz.CrashTheCastle.CrashTheCastle
version: 1.0
description: CrashTheCastleDevRavi
commands:
  start:
    description: Start the game!
    usage: /start
  resethealth:
    description: Over 9000!
    usage: /resethealth
  class:
    description: Over 9000!
    usage: /class